# Version is Being Deprecated
services:
  onboarderr:
    image: python:3.10-slim
    container_name: onboarderr
    working_dir: /app
    volumes:
      - .:/app
      - /media:/media
    ports:
      - "10000:10000"
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    restart: unless-stopped 
